services:
  backend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile.prod
    command: sh -c "gunicorn
      server.asgi:application
      --chdir ./backend
      --bind 0.0.0.0:8000 
      -k uvicorn.workers.UvicornWorker"
    volumes:
      - ./backend:/app/backend
    depends_on:
      - db
      - redis
    networks:
      - backend
    ports:
      - 8000:8000
    expose:
      - 8000
    env_file:
      - ./.env
  db:
    image: postgres:17-bullseye
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend
  redis:
    restart: unless-stopped
    image: redis:7.2.4-alpine
    expose:
      - 6379
    networks:
      - backend
  nginx:
    build: ./docker/nginx
    volumes:
      - static_volume:/app/backend/staticfiles
    ports:
      - 1337:80
    depends_on:
      - backend

volumes:
  static_volume: {}
  db: {}

networks:
  backend:
    # Use a custom driver which takes special options
    driver: bridge
